server:
  port: 8082
  url: http://localhost:${server.port}

application:
  name: Transactions
  basepath: transactions

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: transactions
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console.enabled: true