
name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-microservices:
    runs-on: ubuntu-latest

  

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn --projects :accounts clean install -Dspring.profiles.active=dev

  
    # Step 4: Deploy to Heroku
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
      with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_APP_NAME_ACCOUNTS: ${{ secrets.HEROKU_APP_NAME_TRANSACTIONS }}
   
